name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ${{ secrets.SSH_FILENAME }}
          chmod 600 ${{ secrets.SSH_FILENAME }}

      - name: Configure SSH
        run: |
          cat > ~/.ssh/config <<EOF
          ${{ secrets.SSH_CONFIGURE }}
          EOF

      - name: Deploy
        run: |
          ssh myserver << 'EOF'
            sudo su

            cd ${{ secrets.TARGET_DIR }}

            echo "Pulling latest code..."
            git pull origin main

            echo "Building containers..."
            docker compose build

            echo "Restarting application..."
            docker compose up -d

            echo "Cleaning images..."
            docker image prune -f
          EOF